miniproject/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('quiz/', include('quiz.urls')),
]

quiz/urls.py
from django.urls import path
from .views import welcome,quiz,quiz_home, submit_quiz

app_name = 'quiz'

urlpatterns = [
    path('', welcome, name='welcome'),
    path('quiz/', quiz, name='quiz'),
    path('quizhome/', quiz_home, name='quiz_home'),
    path('submit/', submit_quiz, name='submit_quiz'),
]

quiz/models.py
from django.db import models




class Question(models.Model):
    question_text = models.CharField(max_length=200)

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    is_correct = models.BooleanField(default=False)



        

quiz/forms.py
from django import forms
from .models import choice

class QuizForm(forms.Form):
     def _init_(self, *args, **kwargs):
        questions = kwargs.pop('questions', None)
        super(QuizForm, self)._init_(*args, **kwargs)

        if questions:
            for question in questions:
                choices = [(choice.id, choice.choice_text) for choice in question.choice_set.all()]
                self.fields[f'question_{question.id}'] = forms.ChoiceField(
                    label=question.question_text,
                    choices=choices,
                    widget=forms.RadioSelect
                )

quiz/views.py
from django.shortcuts import render, get_object_or_404
from .models import Question, Choice
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib import messages
from django.http import HttpResponse

def welcome(request):
    return render(request,'quiz/welcome.html')

def quiz(request):
    return render(request,'quiz/quiz.html')

def quiz_home(request):
    
    questions = Question.objects.all()
    context = {'questions': questions}
    return render(request, 'quiz/quiz_home.html', context)


def submit_quiz(request):
    if request.method == 'POST':
        score = 0
        for question_id, submitted_choice_id in request.POST.items():
            if question_id.isdigit():
                try:
                    question = get_object_or_404(Question, pk=question_id)
                    selected_choice = question.choice_set.get(pk=int(submitted_choice_id))
                except (Question.DoesNotExist, Choice.DoesNotExist, ValueError) as e:
                    print(f"Error processing question {question_id}: {e}")
                    selected_choice = None  
                
                if selected_choice and selected_choice.is_correct:
                    score += 1

        request.session['quiz_score'] = score

        messages.success(request, 'QUIZ SUBMITTED!!!')
        
        return render(request,'quiz/submit_quiz.html')



   

quiz/templates/quiz/quiz.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'quiz/style.css' %}">

</head>
<body> <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <h1>Go to quiz</h1>
    <form method="post" action="{% url 'quiz:quiz_home' %}">
        {% csrf_token %}
        <div class="center-button-container">
        <br>
        <button class="center-button">Click me</button>
    </div>
</form>
         
    
</body>
</html>

quiz/templates/quiz/quiz_home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'quiz/style.css' %}">


    <title>Quiz Home</title>
</head>
<body>
    <h1>Quiz Questions</h1>
    
    {% for question in questions %}
        <form method="post" action="{% url 'quiz:submit_quiz' %}">
            {% csrf_token %}
            <fieldset>
                <legend>{{ question.question_text }}</legend>
                
                {% for choice in question.choice_set.all %}
                <label>
                    <input type="radio" name="{{ question.id }}" value="{{ choice.id }}">
                    {{ choice.choice_text }}
                </label><br>
            {% endfor %}
        </fieldset>
        <br>
    {% endfor %}
    <button class="styled-button">Submit Quiz</button>
</form>
</body>
</html>

quiz/templates/quiz/submit_quiz.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'quiz/style.css' %}">

    <title>Quiz Submission</title>
</head>
<body class="container">
    <h1>Quiz Submission</h1>
    
    <p>{% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}
    </p><br>
    <br>
    
    <p>YOUR SCORE IS: {{ request.session.quiz_score }}/10</p>
    
    <a href="{% url 'quiz:quiz_home' %}">Back to Quiz</a>
</body>
</html>

quiz/templates/quiz/welcome.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'quiz/style.css' %}">
    

</head>
<body >
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <h1>WELCOME TO PYTHON QUIZ</h1>
    <form method="post" action="{% url 'quiz:quiz' %}">
        {% csrf_token %}
        <div class="center-button-container">
            <br>
        
        <button class="center-button">Next</button>
    </div>
    </form>
    
</body>
</html>